function [accuracyMean, accuracyStd, flcaMean, fhMean, tieMean, testTime, ...
    accuracyLeaf, accuracyTail, fhStd, tieStd, accuracyTailStd, fh, tie] = ...
    chacf_evaluate(data, tree, feature, tailClass, fraction, method)
[n, nFeature] = size(data);
nFeature = nFeature - 1;
nSelected = round(nFeature * fraction);
rand('seed', 1);
folds = crossvalind('Kfold', n, 10);
start = tic;
[accuracyMean, accuracyStd, flcaMean, fhMean, tieMean, accuracyLeaf, ...
    accuracyTail, fhStd, tieStd, accuracyTailStd, fh, tie] = ...
    FS_Kflod_TopDownSVMClassifier1( ...
    data, 10, tree, feature, nSelected, folds, tailClass, method);
testTime = toc(start);
end
